import { Business, Category, Review } from '@/types/business'

export const mockCategories: Category[] = [
    {
        slug: 'restaurants',
        name: 'Restaurants',
        nameМк: 'Ресторани',
        icon: 'UtensilsCrossed',
        count: 3,
    },
    {
        slug: 'cafes',
        name: 'Cafes',
        nameМк: 'Кафулиња',
        icon: 'Coffee',
        count: 3,
    },
    {
        slug: 'services',
        name: 'Services',
        nameМк: 'Услуги',
        icon: 'Wrench',
        count: 2,
    },
    {
        slug: 'shopping',
        name: 'Shopping',
        nameМк: 'Шопинг',
        icon: 'ShoppingBag',
        count: 2,
    },
]

export const mockBusinesses: Business[] = [
    {
        id: '1',
        placeId: 'ChIJ_1',
        name: 'Destan Restaurant',
        address: 'ul. Dame Gruev 1, Skopje',
        category: 'Restaurants',
        categorySlug: 'restaurants',
        rating: 4.7,
        reviewCount: 124,
        priceLevel: 3,
        photoUrl: '/images/placeholder-restaurant.jpg',
        location: { lat: 41.9981, lng: 21.4254 },
        openNow: true,
        description:
            'Traditional Macedonian cuisine with a modern twist. Known for its warm atmosphere and exceptional grilled dishes.',
    },
    {
        id: '2',
        placeId: 'ChIJ_2',
        name: 'Kaj Marsalot',
        address: 'Bul. Partizanski Odredi 17, Skopje',
        category: 'Restaurants',
        categorySlug: 'restaurants',
        rating: 4.5,
        reviewCount: 89,
        priceLevel: 2,
        photoUrl: '/images/placeholder-restaurant.jpg',
        location: { lat: 42.0024, lng: 21.4312 },
        openNow: true,
        description:
            'Cozy restaurant serving classic Macedonian and Balkan specialties with friendly service.',
    },
    {
        id: '3',
        placeId: 'ChIJ_3',
        name: 'Pelister Restaurant',
        address: 'ul. Makedonija 19, Bitola',
        category: 'Restaurants',
        categorySlug: 'restaurants',
        rating: 4.3,
        reviewCount: 67,
        priceLevel: 2,
        photoUrl: '/images/placeholder-restaurant.jpg',
        location: { lat: 41.0297, lng: 21.3292 },
        openNow: false,
        description:
            'A Bitola landmark serving traditional recipes passed down through generations.',
    },
    {
        id: '4',
        placeId: 'ChIJ_4',
        name: 'Cafe Trend',
        address: 'ul. Orce Nikolov 99, Skopje',
        category: 'Cafes',
        categorySlug: 'cafes',
        rating: 4.6,
        reviewCount: 201,
        priceLevel: 2,
        photoUrl: '/images/placeholder-cafe.jpg',
        location: { lat: 41.998, lng: 21.423 },
        openNow: true,
        description:
            'Popular cafe with excellent espresso and a vibrant atmosphere. Great for remote work.',
    },
    {
        id: '5',
        placeId: 'ChIJ_5',
        name: 'Barista Coffee House',
        address: 'ul. 11 Oktomvri 25, Skopje',
        category: 'Cafes',
        categorySlug: 'cafes',
        rating: 4.4,
        reviewCount: 156,
        priceLevel: 2,
        photoUrl: '/images/placeholder-cafe.jpg',
        location: { lat: 42.001, lng: 21.428 },
        openNow: true,
        description: 'Specialty coffee shop with carefully sourced beans and expert baristas.',
    },
    {
        id: '6',
        placeId: 'ChIJ_6',
        name: 'Old Town Cafe',
        address: 'ul. Bitpazarska, Skopje',
        category: 'Cafes',
        categorySlug: 'cafes',
        rating: 4.2,
        reviewCount: 93,
        priceLevel: 1,
        photoUrl: '/images/placeholder-cafe.jpg',
        location: { lat: 42.0, lng: 21.432 },
        openNow: false,
        description: 'Charming cafe in the Old Bazaar with a relaxed vibe and traditional drinks.',
    },
    {
        id: '7',
        placeId: 'ChIJ_7',
        name: 'AutoMaster Service',
        address: 'ul. Jane Sandanski 120, Skopje',
        category: 'Services',
        categorySlug: 'services',
        rating: 4.8,
        reviewCount: 45,
        priceLevel: 2,
        photoUrl: '/images/placeholder-service.jpg',
        location: { lat: 41.991, lng: 21.418 },
        openNow: true,
        description:
            'Reliable auto repair service with certified mechanics and transparent pricing.',
    },
    {
        id: '8',
        placeId: 'ChIJ_8',
        name: 'TechFix Electronics',
        address: 'City Mall, Skopje',
        category: 'Services',
        categorySlug: 'services',
        rating: 4.1,
        reviewCount: 78,
        priceLevel: 2,
        photoUrl: '/images/placeholder-service.jpg',
        location: { lat: 42.003, lng: 21.42 },
        openNow: true,
        description:
            'Professional electronics repair for phones, laptops, and tablets with quick turnaround times.',
    },
    {
        id: '9',
        placeId: 'ChIJ_9',
        name: 'Vero Hypermarket',
        address: 'Bul. Jane Sandanski 79a, Skopje',
        category: 'Shopping',
        categorySlug: 'shopping',
        rating: 4.0,
        reviewCount: 312,
        priceLevel: 2,
        photoUrl: '/images/placeholder-shop.jpg',
        location: { lat: 41.995, lng: 21.415 },
        openNow: true,
        description:
            'Large hypermarket with a wide selection of groceries, household items, and electronics.',
    },
    {
        id: '10',
        placeId: 'ChIJ_10',
        name: 'Ramstore Mall',
        address: 'ul. Kej 13 Noemvri, Skopje',
        category: 'Shopping',
        categorySlug: 'shopping',
        rating: 4.3,
        reviewCount: 189,
        priceLevel: 3,
        photoUrl: '/images/placeholder-shop.jpg',
        location: { lat: 42.002, lng: 21.434 },
        openNow: true,
        description: 'Modern shopping center with brands, food court, and entertainment.',
    },
]

export const mockReviews: Review[] = [
    {
        id: 'r1',
        businessId: '1',
        userId: 'u1',
        userName: 'Марко Петровски',
        userAvatar: null,
        rating: 5,
        comment:
            'Одлична храна и сервис! Ги препорачувам кебапите и шопската салата. Атмосферата е многу пријатна.',
        createdAt: '2026-02-10T18:30:00Z',
    },
    {
        id: 'r2',
        businessId: '1',
        userId: 'u2',
        userName: 'Ana Ivanova',
        userAvatar: null,
        rating: 4,
        comment:
            'Great food, a bit crowded on weekends but worth the wait. The staff is very friendly.',
        createdAt: '2026-02-08T12:00:00Z',
    },
    {
        id: 'r3',
        businessId: '1',
        userId: 'u3',
        userName: 'Stefan Nikolov',
        userAvatar: null,
        rating: 5,
        comment: 'Best traditional Macedonian food in Skopje! The mixed grill is a must-try.',
        createdAt: '2026-01-28T19:45:00Z',
    },
    {
        id: 'r4',
        businessId: '2',
        userId: 'u4',
        userName: 'Elena Stojanova',
        userAvatar: null,
        rating: 4,
        comment: 'Nice interior and good food. The portions are generous and prices are fair.',
        createdAt: '2026-02-05T14:20:00Z',
    },
    {
        id: 'r5',
        businessId: '2',
        userId: 'u1',
        userName: 'Марко Петровски',
        userAvatar: null,
        rating: 5,
        comment: 'Секогаш одлично! Одличен избор за семејни ручеци.',
        createdAt: '2026-01-30T13:00:00Z',
    },
    {
        id: 'r6',
        businessId: '4',
        userId: 'u5',
        userName: 'Ivana Dimovska',
        userAvatar: null,
        rating: 5,
        comment: 'Best coffee in Skopje! The latte art is always on point and the WiFi is fast.',
        createdAt: '2026-02-12T09:30:00Z',
    },
    {
        id: 'r7',
        businessId: '4',
        userId: 'u6',
        userName: 'David Trajkovski',
        userAvatar: null,
        rating: 4,
        comment:
            'Great atmosphere for working. A bit noisy during rush hours but otherwise perfect.',
        createdAt: '2026-02-01T11:15:00Z',
    },
    {
        id: 'r8',
        businessId: '5',
        userId: 'u7',
        userName: 'Мила Георгиева',
        userAvatar: null,
        rating: 5,
        comment: 'Најдобро кафе во градот! Бариста знае точно што прави. Обожавам го flat white.',
        createdAt: '2026-02-14T10:00:00Z',
    },
    {
        id: 'r9',
        businessId: '7',
        userId: 'u8',
        userName: 'Petar Stojanovski',
        userAvatar: null,
        rating: 5,
        comment: 'Honest and professional service. They fixed my car quickly and at a fair price.',
        createdAt: '2026-02-06T16:00:00Z',
    },
    {
        id: 'r10',
        businessId: '7',
        userId: 'u9',
        userName: 'Kristina Angelova',
        userAvatar: null,
        rating: 5,
        comment: 'Finally a mechanic I can trust! Transparent about costs and very skilled.',
        createdAt: '2026-01-25T14:30:00Z',
    },
    {
        id: 'r11',
        businessId: '3',
        userId: 'u10',
        userName: 'Борче Митевски',
        userAvatar: null,
        rating: 4,
        comment: 'Традиционална храна со одличен квалитет. Убав амбиент во центарот на Битола.',
        createdAt: '2026-02-03T20:00:00Z',
    },
    {
        id: 'r12',
        businessId: '8',
        userId: 'u3',
        userName: 'Stefan Nikolov',
        userAvatar: null,
        rating: 4,
        comment: 'Fixed my phone screen in under an hour. Good work, reasonable prices.',
        createdAt: '2026-02-09T15:45:00Z',
    },
    {
        id: 'r13',
        businessId: '9',
        userId: 'u4',
        userName: 'Elena Stojanova',
        userAvatar: null,
        rating: 4,
        comment: 'Good selection and prices. The fresh produce section is excellent.',
        createdAt: '2026-02-11T17:30:00Z',
    },
    {
        id: 'r14',
        businessId: '10',
        userId: 'u5',
        userName: 'Ivana Dimovska',
        userAvatar: null,
        rating: 4,
        comment: 'Great mall with lots of shops and a nice food court. Parking can be tricky.',
        createdAt: '2026-02-07T12:00:00Z',
    },
    {
        id: 'r15',
        businessId: '6',
        userId: 'u6',
        userName: 'David Trajkovski',
        userAvatar: null,
        rating: 4,
        comment:
            'Lovely spot in the Old Bazaar. The Turkish coffee is authentic and the vibe is relaxed.',
        createdAt: '2026-01-20T16:00:00Z',
    },
]
